services:
# --- nginx --- #
  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: unless-stopped
    ports:
      - "443:443"
    volumes:
    # main config wrapper
      - ${NginxConfig}/nginx.conf:/etc/nginx/nginx.conf:ro
    # template config, containing actual config
      - ${NginxConfig}/templates/default.conf.template:/etc/nginx/templates/default.conf.template:ro
    # ssl certs
      - ${CertbotDir}/conf:/etc/letsencrypt:ro
    environment:
      BASE_DOMAIN: ${BaseDomain}
    networks:
      - net-nextcloud
      - net-host
      - net-nginx-interconnect #network to connect "external" to this nginx instance
    depends_on:
      - cloudflare-ddns

# --- nextcloud --- #
  nextcloud:
    image: nextcloud
    container_name: nextcloud
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: ${NextCloudDBPW}
      POSTGRES_DB: "nextcloud"
      POSTGRES_USER: "nextcloud"
      POSTGRESQL_HOST: nextclouddb
      PHP_MEMORY_LIMIT: 1G
      PHP_UPLOAD_LIMIT: 16G
    expose:
      - "80"
    networks:
      - net-nextcloud
      - net-nextcloud-intern
      - net-host # requires an active internet connection for some tools
    volumes:
      - ${NextCloudDir}:/var/www/html
    depends_on:
      - nextcloud-cron
      - nextclouddb
      - nginx

  nextcloud-cron:
    image: nextcloud
    container_name: nextcloud-cron
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: ${NextCloudDBPW}
      POSTGRES_DB: "nextcloud"
      POSTGRES_USER: "nextcloud"
      POSTGRESQL_HOST: nextclouddb
    volumes:
      - ${NextCloudDir}:/var/www/html
    entrypoint: /cron.sh
    networks:
      - net-nextcloud-intern
    depends_on:
      - nextclouddb

  nextclouddb:
    image: postgres
    container_name: nextclouddb
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: ${NextCloudDBPW}
      POSTGRES_DB: "nextcloud"
      POSTGRES_USER: "nextcloud"
    volumes:
      - ${NextCloudDBDir}:/var/lib/postgresql
    networks:
      - net-nextcloud-intern

# --- Cloudflare DDNS --- #
  cloudflare-ddns:
    image: favonia/cloudflare-ddns:1.15.1
    container_name: cloudflare-ddns
    network_mode: host
    restart: unless-stopped
    user: "1000:1000"
    read_only: true
    cap_drop: [all]
    security_opt: [no-new-privileges:true]
    environment:
      - CLOUDFLARE_API_TOKEN=${CloudflareAPIToken}
      - DOMAINS=${CloudflareDomains}

# --- Certbot --- #
  certbot:  
    image: certbot/dns-cloudflare
    container_name: certbot
    environment:
      - CLOUDFLARE_API_TOKEN=${CloudflareAPIToken}
    volumes:
      - ${CertbotDir}/conf:/etc/letsencrypt
      - ${CertbotDir}/logs:/var/log/letsencrypt
      - ${CertbotIni}:/etc/certbot/cloudflare.ini:ro
    entrypoint: > # create initial certificate and the try to renew every 12h
      sh -c "certbot certonly --dns-cloudflare --dns-cloudflare-credentials /etc/certbot/cloudflare.ini --non-interactive --agree-tos --no-eff-email --email ${CertbotEmail} -d ${BaseDomain} -d '*.${BaseDomain}' && false || while true; do certbot renew --dns-cloudflare --dns-cloudflare-propagation-seconds 30 && false || sleep 12h; done"
    restart: unless-stopped
    networks:
     - net-host

networks:
  net-nextcloud:
    driver: bridge
    internal: true
  net-nextcloud-intern:
    driver: bridge
    internal: true
  net-host:
    driver: bridge
  net-nginx-interconnect: #network to connect "external" to this nginx instance
    driver: bridge
    internal: true
    name: nginx-interconnect